#!/bin/sh
# shellcheck disable=SC2016 # as crases são do Markdown esperado, não expansão
# Testes do sdd-context.sh (spec 018 FR-1) com um gh falso e um repositório de teste.
set -eu

root="$(cd "$(dirname "$0")/.." && pwd)"
tmp="$(mktemp -d)"
trap 'rm -rf "$tmp"' EXIT
fail() { echo "FALHOU: $*" >&2; exit 1; }

# gh falso: a issue vem de $G/issue.json.
G="$tmp/gh"; mkdir -p "$G" "$tmp/bin"
cat > "$tmp/bin/gh" <<'SH'
#!/bin/sh
jq=""; url=""
shift # api
while [ $# -gt 0 ]; do
  case "$1" in --jq) jq="$2"; shift 2 ;; *) url="$1"; shift ;; esac
done
case "$url" in */issues/7) jq -r "$jq" "$G/issue.json" ;; *) echo "gh falso: $url" >&2; exit 1 ;; esac
SH
chmod +x "$tmp/bin/gh"
export PATH="$tmp/bin:$PATH" G

r="$tmp/repo"; mkdir -p "$r/scripts" "$r/specs/003-dist" "$r/specs/004-outra"
cp "$root/template/common/scripts/sdd-context.sh" "$r/scripts/"
cat > "$r/specs/003-dist/spec.md" <<'MD'
# 003 — Distribuição

- **Código afetado:** `scripts/build.sh` e `pack.sh` (novo), `CLAUDE.md`, `docs/`

- **FR-1** Linha do FR-1, conforme a D2.
- **FR-2** Linha do FR-2.
- **FR-3** Linha do FR-3.
- **AC-1** Linha do AC-1.
- **AC-2** Linha do AC-2.
MD
printf '# 004\n\n- **FR-1** Outra spec.\n' > "$r/specs/004-outra/spec.md"
cat > "$r/specs/ANALYSIS.md" <<'MD'
| D | Pergunta | Opções | Resposta |
|---|---|---|---|
| D2 | Como empacotar? | (a) tar | **(a)** |
| D3 | Outra? | (a) x | **(a)** |
MD
printf '# CLAUDE\n\n## Armadilhas\n\n- O build.sh precisa do Go.\n- Outra armadilha.\n\n## Outra\n\n- build.sh fora da seção.\n' > "$r/CLAUDE.md"
printf '#!/bin/sh\n# Uso: build.sh [ALVO]\nmain() {\n  :\n}\nhelper_x() { :; }\n' > "$r/scripts/build.sh"
mkdir "$r/docs"
cd "$r"
git init -q
jq -n '{title: "T1: empacotar", body: "## O que fazer\n\n- empacotar\n\n**Spec(s):** 003 FR-1, FR-2 a FR-3, AC-1 · **Épico:** #5\n\n\n---\n_Generated by [Claude Code](https://claude.ai/code)_"}' > "$G/issue.json"
c="sh scripts/sdd-context.sh --repo o/r"

# 018 AC-1: só as linhas citadas da spec (com a faixa expandida), não o resto.
out="$($c '#7')" || fail "context falhou: $out"
for l in '# Ticket #7: T1: empacotar' '- **FR-1** Linha do FR-1, conforme a D2.' '- **FR-2** Linha do FR-2.' \
  '- **FR-3** Linha do FR-3.' '- **AC-1** Linha do AC-1.'; do
  printf '%s\n' "$out" | grep -qxF -- "$l" || fail "sem '$l': $out"
done
printf '%s\n' "$out" | grep -qF 'AC-2' && fail "trouxe o AC-2, não citado: $out"
printf '%s\n' "$out" | grep -qF 'Outra spec' && fail "trouxe outra spec: $out"
printf '%s\n' "$out" | grep -qF '_Generated by' && fail "trouxe o rodapé da issue: $out"
# Decisão citada, arquivos com assinaturas, armadilha do arquivo e comandos de entrega.
printf '%s\n' "$out" | grep -qF '| D2 | Como empacotar?' || fail "sem a decisão D2: $out"
printf '%s\n' "$out" | grep -qF '| D3 |' && fail "trouxe a D3, não citada: $out"
for l in '- `scripts/build.sh`' '  - # Uso: build.sh [ALVO]' '  - main()' '  - helper_x()' '- `scripts/pack.sh` (novo)' \
  '- `CLAUDE.md`' '- `docs/` (pasta)' '- O build.sh precisa do Go.'; do
  printf '%s\n' "$out" | grep -qxF -- "$l" || fail "sem '$l': $out"
done
printf '%s\n' "$out" | grep -qF 'build.sh fora da seção' && fail "trouxe linha fora das armadilhas: $out"
printf '%s\n' "$out" | grep -qF '/sdd-pr.sh --spec 003 --no-wait' || fail "sem a entrega: $out"

# 018 AC-1: o teto. Primeiro os arquivos perdem as assinaturas; depois, o corte.
full="$(printf '%s\n' "$out" | wc -c)"
out="$(SDD_CONTEXT_MAX=$((full - 10)) $c '#7')" || fail "teto 1 falhou"
printf '%s\n' "$out" | grep -qF 'helper_x' && fail "no teto, manteve as assinaturas: $out"
printf '%s\n' "$out" | grep -qxF -- '- `scripts/build.sh`' || fail "no teto, perdeu o caminho: $out"
[ "$(printf '%s\n' "$out" | wc -c)" -le $((full - 10)) ] || fail "passou do teto 1"
out="$(SDD_CONTEXT_MAX=300 $c '#7')" || fail "teto 2 falhou"
[ "$(printf '%s\n' "$out" | wc -c)" -le 300 ] || fail "passou do teto: $(printf '%s\n' "$out" | wc -c)"
printf '%s\n' "$out" | tail -n 1 | grep -qF 'pacote cortado no teto de 300 bytes' || fail "sem o aviso de corte: $out"

# Uso inválido: 3.
rc=0; $c 'x' > /dev/null 2>&1 || rc=$?
[ "$rc" -eq 3 ] || fail "uso inválido saiu com $rc"
rc=0; SDD_CONTEXT_MAX=abc $c 7 > /dev/null 2>&1 || rc=$?
[ "$rc" -eq 3 ] || fail "teto inválido saiu com $rc"
echo "sdd-context: ok"
