#!/bin/sh
# shellcheck disable=SC2013,SC2016 # listas sem espaços (specs, ids, Dn) e crases do Markdown entre aspas simples
# sdd-context: o pacote de contexto de um ticket, sem LLM (spec 018 FR-1), para uma
# sessão nova começar pequena em vez de ler specs inteiras.
#
# Uso: sdd-context.sh [--repo DONO/REPO] '#N'
#   Imprime em Markdown: a issue; só as linhas dos FR/NFR/AC citados em "Spec(s)"
#   (com "FR-1 a FR-3" expandido); as decisões Dn citadas (specs/ANALYSIS.md); os
#   arquivos prováveis ("Código afetado" das specs citadas) com as assinaturas
#   (funções e linha de uso dos scripts); as armadilhas do CLAUDE.md que citam esses
#   arquivos; e os comandos de entrega.
#   SDD_CONTEXT_MAX: teto em bytes (padrão 16000); acima dele, os arquivos entram só
#   com o caminho e, se ainda não couber, o pacote é cortado no teto com um aviso.
# Códigos: 0 ok; 1 falha do gh; 3 uso. Requer gh e jq.
set -eu

usage() { sed -n '3,14p' "$0"; exit 3; }
repo=""
[ "${1:-}" != --repo ] || { repo="${2:?}"; shift 2; }
[ $# -eq 1 ] || usage
n="${1#\#}"
case "$n" in '' | *[!0-9]*) usage ;; esac
max="${SDD_CONTEXT_MAX:-16000}"
case "$max" in '' | *[!0-9]*) echo "sdd-context: SDD_CONTEXT_MAX inválido: $max" >&2; exit 3 ;; esac
root="$(git rev-parse --show-toplevel 2> /dev/null || pwd)"
here="${SDD_SCRIPTS_DIR:-$(cd "$(dirname "$0")" && pwd)}"
sdir="${here#"$root"/}"
if [ -z "$repo" ]; then
  url="$(git remote get-url origin 2> /dev/null || true)"
  repo="$(printf '%s\n' "$url" | sed -E 's#\.git$##; s#^.*[:/]([^/]+/[^/]+)$#\1#')"
fi
[ -n "$repo" ] || { echo "sdd-context: repositório desconhecido (use --repo)" >&2; exit 3; }
tmp="$(mktemp -d)"
trap 'rm -rf "$tmp"' EXIT

gh api "repos/$repo/issues/$n" --jq '"\(.title)\n\(.body // "")"' > "$tmp/issue" \
  || { echo "sdd-context: falha ao ler a issue #$n" >&2; exit 1; }
title="$(head -n 1 "$tmp/issue")"
# O corpo sem o rodapé de atribuição.
sed 1d "$tmp/issue" | awk '{ l[NR] = $0 } /^---$/ { cut = NR } END {
  if (!(cut && l[cut + 1] ~ /^_Generated by/)) cut = NR + 1
  while (cut > 1 && l[cut - 1] == "") cut--
  for (i = 1; i < cut; i++) print l[i] }' > "$tmp/body"

# "Spec(s): 017 FR-2, FR-3 a FR-5, AC-2 · Épico" -> linhas "spec<TAB>id".
ids="$(sed -n 's/^\*\*Spec(s):\*\* \(.*\) · \*\*Épico.*/\1/p' "$tmp/body" | head -n 1)"
printf '%s\n' "$ids" | tr ',' '\n' | awk '
  { gsub(/^ +| +$/, "") }
  match($0, /^[0-9][0-9][0-9]/) { spec = substr($0, 1, 3); $0 = substr($0, 4); gsub(/^ +/, "") }
  $0 ~ /^(FR|NFR|AC)-[0-9]+ a (FR|NFR|AC)-[0-9]+$/ && spec != "" {
    split($0, p, " a "); k = p[1]; sub(/-[0-9]+$/, "", k)
    a = p[1]; sub(/^[A-Z]+-/, "", a); b = p[2]; sub(/^[A-Z]+-/, "", b)
    for (i = a + 0; i <= b + 0; i++) print spec "\t" k "-" i
    next }
  $0 ~ /^(FR|NFR|AC)-[0-9]+$/ && spec != "" { print spec "\t" $0; next }
  spec != "" && $0 == "" { print spec "\t" }' | awk '!seen[$0]++' > "$tmp/ids"

{
  echo "# Ticket #$n: $title"
  echo
  cat "$tmp/body"
} > "$tmp/s1"

: > "$tmp/s2"; : > "$tmp/files"
for spec in $(cut -f1 "$tmp/ids" | awk '!seen[$0]++'); do
  f="$(find "$root/specs" -maxdepth 2 -path "*/$spec-*/spec.md" 2> /dev/null | head -n 1)"
  [ -n "$f" ] || continue
  {
    echo; echo "## Spec $spec (${f#"$root"/})"; echo
    sed -n '1s/^# //p' "$f"
    for id in $(awk -F '\t' -v s="$spec" '$1 == s && $2 != "" { print $2 }' "$tmp/ids"); do
      grep -E "^- \*\*$id\*\* " "$f" || true
    done
  } >> "$tmp/s2"
  # Caminhos entre crases da linha "Código afetado"; um nome sem barra que não existe
  # na raiz herda a pasta do caminho anterior ("`a/x.sh` e `y.sh`").
  d=""
  for p in $(sed -n 's/^- \*\*Código afetado:\*\* //p' "$f" | grep -o '`[^`]*`' | tr -d '`'); do
    case "$p" in
      */*) d="${p%/*}/"; echo "$p" ;;
      *) if [ -e "$root/$p" ] || [ -z "$d" ]; then echo "$p"; else echo "$d$p"; fi ;;
    esac
  done >> "$tmp/files"
done

# Decisões citadas na issue ou nas linhas da spec.
: > "$tmp/s3"
for d in $(cat "$tmp/body" "$tmp/s2" | grep -oE '(^|[^A-Za-z0-9])D[0-9]+' | sed 's/^[^D]*//' | awk '!seen[$0]++'); do
  grep -E "^\| $d \|" "$root/specs/ANALYSIS.md" 2> /dev/null >> "$tmp/s3" || true
done
[ ! -s "$tmp/s3" ] || { printf '\n## Decisões\n\n| D | Pergunta | Opções | Resposta |\n|---|---|---|---|\n'; cat "$tmp/s3"; } > "$tmp/s3b"
[ -f "$tmp/s3b" ] || : > "$tmp/s3b"

# Arquivos prováveis: com assinaturas (s4) e só caminhos (s4p).
awk '!seen[$0]++' "$tmp/files" > "$tmp/f"
: > "$tmp/s4"; : > "$tmp/s4p"; : > "$tmp/trap"
if [ -s "$tmp/f" ]; then
  printf '\n## Arquivos prováveis\n\n' | tee "$tmp/s4" > "$tmp/s4p"
  while read -r p; do
    echo "- \`$p\`" >> "$tmp/s4p"
    if [ -f "$root/$p" ]; then
      echo "- \`$p\`" >> "$tmp/s4"
      case "$p" in
        *.sh) { grep -m 1 -E '^# Uso:' "$root/$p" || true; grep -E '^[a-z_]+\(\) \{' "$root/$p" | sed 's/ {.*//' || true; } | sed 's/^/  - /' >> "$tmp/s4" ;;
      esac
    elif [ -d "$root/$p" ]; then
      echo "- \`$p\` (pasta)" >> "$tmp/s4"
    else
      echo "- \`$p\` (novo)" >> "$tmp/s4"
    fi
    b="$(basename "$p")"
    [ ! -f "$root/CLAUDE.md" ] || awk '/^## Armadilhas/ { a = 1; next } a && /^## / { a = 0 } a && /^- /' "$root/CLAUDE.md" \
      | grep -F -- "$b" >> "$tmp/trap" || true
  done < "$tmp/f"
fi
: > "$tmp/s5"
[ ! -s "$tmp/trap" ] || { printf '\n## Armadilhas\n\n'; awk '!seen[$0]++' "$tmp/trap"; } > "$tmp/s5"

spec1="$(cut -f1 "$tmp/ids" | head -n 1)"
cat > "$tmp/s6" <<EOT

## Entrega

- Branch \`<tipo>/$n-<descrição>\` a partir da \`main\`; commits em Conventional Commits.
- \`make ci\` antes do push; \`sh $sdir/sdd-pr.sh --spec ${spec1:-—} --no-wait\` abre o PR e grava o checkpoint.
- Depois do PR: \`sh $sdir/sdd-checkpoint.sh save "feito" "próximo"\` e encerre a sessão.
EOT

cat "$tmp/s1" "$tmp/s2" "$tmp/s3b" "$tmp/s5" "$tmp/s6" "$tmp/s4" > "$tmp/out"
if [ "$(wc -c < "$tmp/out")" -gt "$max" ]; then
  cat "$tmp/s1" "$tmp/s2" "$tmp/s3b" "$tmp/s5" "$tmp/s6" "$tmp/s4p" > "$tmp/out"
fi
if [ "$(wc -c < "$tmp/out")" -gt "$max" ]; then
  note="[sdd-context: pacote cortado no teto de $max bytes (SDD_CONTEXT_MAX)]"
  # Corta numa quebra de linha, para não partir um caractere UTF-8.
  head -c "$((max - ${#note} - 2))" "$tmp/out" | sed '$d'
  echo "$note"
else
  cat "$tmp/out"
fi
